# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PrudishCamera' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PrudishCamera

pod 'AlertMaker', '~> 0.1.25'

end
